### ISSUE TITLE
Standalonethirdperson no longer working

### ISSUE THREAD

**Issue by MunndoVT** [gompoc/VRChatMods#10]
Hello! This mod stopped working yesterday, and after checking in with melonloader stuff, they gave me this answer:

"I looked into it and emmVRC disabled its old risky check api and it appears that standalonethirdperson checks for risky itself instead of using VRCUK."

They advised me to make an issue here, so, here it is. Do you think you could look into it? This is an amazing mod for those of us who don't have VR sets, so thanks in advance for checking this out.

**Comment by gompoc** [comment]
One word: EAC
