### ISSUE TITLE
please help ;(

### ISSUE THREAD

**Issue by Ishikiopy** [gompoc/VRChatMods#9]
![image](https://user-images.githubusercontent.com/105979511/175105842-2f491c13-d168-4c05-b64e-467ff2e9069f.png)

**Comment by gompoc** [comment]
Hi there, please make sure:
A. Your game is up to date
B. You're using MelonLoader v0.5.3
C. The mod is up to date, the latest version can be found here: https://api.vrcmg.com/v1/mods/download/201

**Comment by Ishikiopy** [comment]
I don't get it I did everything but they wont appear in game...
![image](https://user-images.githubusercontent.com/105979511/175110773-dc2cfbed-5b8c-4fd2-b585-eb3e733363bd.png)
![image](https://user-images.githubusercontent.com/105979511/175110715-1bc69c03-cedb-46cc-81b8-ba764f70bd11.png)

**Comment by gompoc** [comment]
Can you send a log?

**Comment by Ishikiopy** [comment]
[Latest.log](https://github.com/gompoc/VRChatMods/files/8967040/Latest.log)
sorry for my late reply

**Comment by Ishikiopy** [comment]
Any idea what could be the issue? I still got no clue

**Comment by gompoc** [comment]
Sorry about the delayed response. Please try updating to MelonLoader v0.5.4 and trying again. Let me know how it goes.

**Comment by Ishikiopy** [comment]
I actually kind of changed my plans, I will focus on somehow getting a working ActionMenu, thank you tho! <3

**Comment by gompoc** [comment]
One word: EAC
